version: "3.8"
services:
    node:
        container_name: node
        build: ./app
        ports:
            - "3000:8080"
    nginx:
        depends_on:
            - node
        container_name: nginx
        build: ./nginx
        ports:
            - "80:80"
